// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto_files/pipeline_interfaces.proto

package de.idp.pipeline;

public final class PipelineInterfaces {
  private PipelineInterfaces() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface Grid_dataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:provenance_system.Grid_data)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.provenance_system.measurement_message measurement = 1;</code>
     */
    boolean hasMeasurement();
    /**
     * <code>.provenance_system.measurement_message measurement = 1;</code>
     */
    de.idp.pipeline.PipelineInterfaces.measurement_message getMeasurement();
    /**
     * <code>.provenance_system.measurement_message measurement = 1;</code>
     */
    de.idp.pipeline.PipelineInterfaces.measurement_messageOrBuilder getMeasurementOrBuilder();
  }
  /**
   * <pre>
   * Grid_data message
   * composition of meter- and measurement_message
   * in compliance with the data model provided from grid data
   * </pre>
   *
   * Protobuf type {@code provenance_system.Grid_data}
   */
  public  static final class Grid_data extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:provenance_system.Grid_data)
      Grid_dataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Grid_data.newBuilder() to construct.
    private Grid_data(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Grid_data() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Grid_data(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              de.idp.pipeline.PipelineInterfaces.measurement_message.Builder subBuilder = null;
              if (measurement_ != null) {
                subBuilder = measurement_.toBuilder();
              }
              measurement_ = input.readMessage(de.idp.pipeline.PipelineInterfaces.measurement_message.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(measurement_);
                measurement_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return de.idp.pipeline.PipelineInterfaces.internal_static_provenance_system_Grid_data_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return de.idp.pipeline.PipelineInterfaces.internal_static_provenance_system_Grid_data_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              de.idp.pipeline.PipelineInterfaces.Grid_data.class, de.idp.pipeline.PipelineInterfaces.Grid_data.Builder.class);
    }

    public static final int MEASUREMENT_FIELD_NUMBER = 1;
    private de.idp.pipeline.PipelineInterfaces.measurement_message measurement_;
    /**
     * <code>.provenance_system.measurement_message measurement = 1;</code>
     */
    public boolean hasMeasurement() {
      return measurement_ != null;
    }
    /**
     * <code>.provenance_system.measurement_message measurement = 1;</code>
     */
    public de.idp.pipeline.PipelineInterfaces.measurement_message getMeasurement() {
      return measurement_ == null ? de.idp.pipeline.PipelineInterfaces.measurement_message.getDefaultInstance() : measurement_;
    }
    /**
     * <code>.provenance_system.measurement_message measurement = 1;</code>
     */
    public de.idp.pipeline.PipelineInterfaces.measurement_messageOrBuilder getMeasurementOrBuilder() {
      return getMeasurement();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (measurement_ != null) {
        output.writeMessage(1, getMeasurement());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (measurement_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getMeasurement());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof de.idp.pipeline.PipelineInterfaces.Grid_data)) {
        return super.equals(obj);
      }
      de.idp.pipeline.PipelineInterfaces.Grid_data other = (de.idp.pipeline.PipelineInterfaces.Grid_data) obj;

      boolean result = true;
      result = result && (hasMeasurement() == other.hasMeasurement());
      if (hasMeasurement()) {
        result = result && getMeasurement()
            .equals(other.getMeasurement());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasMeasurement()) {
        hash = (37 * hash) + MEASUREMENT_FIELD_NUMBER;
        hash = (53 * hash) + getMeasurement().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static de.idp.pipeline.PipelineInterfaces.Grid_data parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.idp.pipeline.PipelineInterfaces.Grid_data parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.idp.pipeline.PipelineInterfaces.Grid_data parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.idp.pipeline.PipelineInterfaces.Grid_data parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.idp.pipeline.PipelineInterfaces.Grid_data parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.idp.pipeline.PipelineInterfaces.Grid_data parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.idp.pipeline.PipelineInterfaces.Grid_data parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static de.idp.pipeline.PipelineInterfaces.Grid_data parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static de.idp.pipeline.PipelineInterfaces.Grid_data parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static de.idp.pipeline.PipelineInterfaces.Grid_data parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static de.idp.pipeline.PipelineInterfaces.Grid_data parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static de.idp.pipeline.PipelineInterfaces.Grid_data parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(de.idp.pipeline.PipelineInterfaces.Grid_data prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Grid_data message
     * composition of meter- and measurement_message
     * in compliance with the data model provided from grid data
     * </pre>
     *
     * Protobuf type {@code provenance_system.Grid_data}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:provenance_system.Grid_data)
        de.idp.pipeline.PipelineInterfaces.Grid_dataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return de.idp.pipeline.PipelineInterfaces.internal_static_provenance_system_Grid_data_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return de.idp.pipeline.PipelineInterfaces.internal_static_provenance_system_Grid_data_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                de.idp.pipeline.PipelineInterfaces.Grid_data.class, de.idp.pipeline.PipelineInterfaces.Grid_data.Builder.class);
      }

      // Construct using de.idp.pipeline.PipelineInterfaces.Grid_data.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (measurementBuilder_ == null) {
          measurement_ = null;
        } else {
          measurement_ = null;
          measurementBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return de.idp.pipeline.PipelineInterfaces.internal_static_provenance_system_Grid_data_descriptor;
      }

      public de.idp.pipeline.PipelineInterfaces.Grid_data getDefaultInstanceForType() {
        return de.idp.pipeline.PipelineInterfaces.Grid_data.getDefaultInstance();
      }

      public de.idp.pipeline.PipelineInterfaces.Grid_data build() {
        de.idp.pipeline.PipelineInterfaces.Grid_data result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public de.idp.pipeline.PipelineInterfaces.Grid_data buildPartial() {
        de.idp.pipeline.PipelineInterfaces.Grid_data result = new de.idp.pipeline.PipelineInterfaces.Grid_data(this);
        if (measurementBuilder_ == null) {
          result.measurement_ = measurement_;
        } else {
          result.measurement_ = measurementBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof de.idp.pipeline.PipelineInterfaces.Grid_data) {
          return mergeFrom((de.idp.pipeline.PipelineInterfaces.Grid_data)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(de.idp.pipeline.PipelineInterfaces.Grid_data other) {
        if (other == de.idp.pipeline.PipelineInterfaces.Grid_data.getDefaultInstance()) return this;
        if (other.hasMeasurement()) {
          mergeMeasurement(other.getMeasurement());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        de.idp.pipeline.PipelineInterfaces.Grid_data parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (de.idp.pipeline.PipelineInterfaces.Grid_data) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private de.idp.pipeline.PipelineInterfaces.measurement_message measurement_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          de.idp.pipeline.PipelineInterfaces.measurement_message, de.idp.pipeline.PipelineInterfaces.measurement_message.Builder, de.idp.pipeline.PipelineInterfaces.measurement_messageOrBuilder> measurementBuilder_;
      /**
       * <code>.provenance_system.measurement_message measurement = 1;</code>
       */
      public boolean hasMeasurement() {
        return measurementBuilder_ != null || measurement_ != null;
      }
      /**
       * <code>.provenance_system.measurement_message measurement = 1;</code>
       */
      public de.idp.pipeline.PipelineInterfaces.measurement_message getMeasurement() {
        if (measurementBuilder_ == null) {
          return measurement_ == null ? de.idp.pipeline.PipelineInterfaces.measurement_message.getDefaultInstance() : measurement_;
        } else {
          return measurementBuilder_.getMessage();
        }
      }
      /**
       * <code>.provenance_system.measurement_message measurement = 1;</code>
       */
      public Builder setMeasurement(de.idp.pipeline.PipelineInterfaces.measurement_message value) {
        if (measurementBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          measurement_ = value;
          onChanged();
        } else {
          measurementBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.provenance_system.measurement_message measurement = 1;</code>
       */
      public Builder setMeasurement(
          de.idp.pipeline.PipelineInterfaces.measurement_message.Builder builderForValue) {
        if (measurementBuilder_ == null) {
          measurement_ = builderForValue.build();
          onChanged();
        } else {
          measurementBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.provenance_system.measurement_message measurement = 1;</code>
       */
      public Builder mergeMeasurement(de.idp.pipeline.PipelineInterfaces.measurement_message value) {
        if (measurementBuilder_ == null) {
          if (measurement_ != null) {
            measurement_ =
              de.idp.pipeline.PipelineInterfaces.measurement_message.newBuilder(measurement_).mergeFrom(value).buildPartial();
          } else {
            measurement_ = value;
          }
          onChanged();
        } else {
          measurementBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.provenance_system.measurement_message measurement = 1;</code>
       */
      public Builder clearMeasurement() {
        if (measurementBuilder_ == null) {
          measurement_ = null;
          onChanged();
        } else {
          measurement_ = null;
          measurementBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.provenance_system.measurement_message measurement = 1;</code>
       */
      public de.idp.pipeline.PipelineInterfaces.measurement_message.Builder getMeasurementBuilder() {
        
        onChanged();
        return getMeasurementFieldBuilder().getBuilder();
      }
      /**
       * <code>.provenance_system.measurement_message measurement = 1;</code>
       */
      public de.idp.pipeline.PipelineInterfaces.measurement_messageOrBuilder getMeasurementOrBuilder() {
        if (measurementBuilder_ != null) {
          return measurementBuilder_.getMessageOrBuilder();
        } else {
          return measurement_ == null ?
              de.idp.pipeline.PipelineInterfaces.measurement_message.getDefaultInstance() : measurement_;
        }
      }
      /**
       * <code>.provenance_system.measurement_message measurement = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          de.idp.pipeline.PipelineInterfaces.measurement_message, de.idp.pipeline.PipelineInterfaces.measurement_message.Builder, de.idp.pipeline.PipelineInterfaces.measurement_messageOrBuilder> 
          getMeasurementFieldBuilder() {
        if (measurementBuilder_ == null) {
          measurementBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              de.idp.pipeline.PipelineInterfaces.measurement_message, de.idp.pipeline.PipelineInterfaces.measurement_message.Builder, de.idp.pipeline.PipelineInterfaces.measurement_messageOrBuilder>(
                  getMeasurement(),
                  getParentForChildren(),
                  isClean());
          measurement_ = null;
        }
        return measurementBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:provenance_system.Grid_data)
    }

    // @@protoc_insertion_point(class_scope:provenance_system.Grid_data)
    private static final de.idp.pipeline.PipelineInterfaces.Grid_data DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new de.idp.pipeline.PipelineInterfaces.Grid_data();
    }

    public static de.idp.pipeline.PipelineInterfaces.Grid_data getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Grid_data>
        PARSER = new com.google.protobuf.AbstractParser<Grid_data>() {
      public Grid_data parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Grid_data(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Grid_data> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Grid_data> getParserForType() {
      return PARSER;
    }

    public de.idp.pipeline.PipelineInterfaces.Grid_data getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface measurement_messageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:provenance_system.measurement_message)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string meter_id = 1;</code>
     */
    java.lang.String getMeterId();
    /**
     * <code>string meter_id = 1;</code>
     */
    com.google.protobuf.ByteString
        getMeterIdBytes();

    /**
     * <code>string metric_id = 2;</code>
     */
    java.lang.String getMetricId();
    /**
     * <code>string metric_id = 2;</code>
     */
    com.google.protobuf.ByteString
        getMetricIdBytes();

    /**
     * <code>int64 timestamp = 3;</code>
     */
    long getTimestamp();

    /**
     * <code>double value = 4;</code>
     */
    double getValue();
  }
  /**
   * <pre>
   * measurement_message
   * </pre>
   *
   * Protobuf type {@code provenance_system.measurement_message}
   */
  public  static final class measurement_message extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:provenance_system.measurement_message)
      measurement_messageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use measurement_message.newBuilder() to construct.
    private measurement_message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private measurement_message() {
      meterId_ = "";
      metricId_ = "";
      timestamp_ = 0L;
      value_ = 0D;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private measurement_message(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              meterId_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              metricId_ = s;
              break;
            }
            case 24: {

              timestamp_ = input.readInt64();
              break;
            }
            case 33: {

              value_ = input.readDouble();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return de.idp.pipeline.PipelineInterfaces.internal_static_provenance_system_measurement_message_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return de.idp.pipeline.PipelineInterfaces.internal_static_provenance_system_measurement_message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              de.idp.pipeline.PipelineInterfaces.measurement_message.class, de.idp.pipeline.PipelineInterfaces.measurement_message.Builder.class);
    }

    public static final int METER_ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object meterId_;
    /**
     * <code>string meter_id = 1;</code>
     */
    public java.lang.String getMeterId() {
      java.lang.Object ref = meterId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        meterId_ = s;
        return s;
      }
    }
    /**
     * <code>string meter_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMeterIdBytes() {
      java.lang.Object ref = meterId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        meterId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int METRIC_ID_FIELD_NUMBER = 2;
    private volatile java.lang.Object metricId_;
    /**
     * <code>string metric_id = 2;</code>
     */
    public java.lang.String getMetricId() {
      java.lang.Object ref = metricId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        metricId_ = s;
        return s;
      }
    }
    /**
     * <code>string metric_id = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMetricIdBytes() {
      java.lang.Object ref = metricId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        metricId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 3;
    private long timestamp_;
    /**
     * <code>int64 timestamp = 3;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    public static final int VALUE_FIELD_NUMBER = 4;
    private double value_;
    /**
     * <code>double value = 4;</code>
     */
    public double getValue() {
      return value_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getMeterIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, meterId_);
      }
      if (!getMetricIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, metricId_);
      }
      if (timestamp_ != 0L) {
        output.writeInt64(3, timestamp_);
      }
      if (value_ != 0D) {
        output.writeDouble(4, value_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getMeterIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, meterId_);
      }
      if (!getMetricIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, metricId_);
      }
      if (timestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, timestamp_);
      }
      if (value_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, value_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof de.idp.pipeline.PipelineInterfaces.measurement_message)) {
        return super.equals(obj);
      }
      de.idp.pipeline.PipelineInterfaces.measurement_message other = (de.idp.pipeline.PipelineInterfaces.measurement_message) obj;

      boolean result = true;
      result = result && getMeterId()
          .equals(other.getMeterId());
      result = result && getMetricId()
          .equals(other.getMetricId());
      result = result && (getTimestamp()
          == other.getTimestamp());
      result = result && (
          java.lang.Double.doubleToLongBits(getValue())
          == java.lang.Double.doubleToLongBits(
              other.getValue()));
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + METER_ID_FIELD_NUMBER;
      hash = (53 * hash) + getMeterId().hashCode();
      hash = (37 * hash) + METRIC_ID_FIELD_NUMBER;
      hash = (53 * hash) + getMetricId().hashCode();
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimestamp());
      hash = (37 * hash) + VALUE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getValue()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static de.idp.pipeline.PipelineInterfaces.measurement_message parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.idp.pipeline.PipelineInterfaces.measurement_message parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.idp.pipeline.PipelineInterfaces.measurement_message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.idp.pipeline.PipelineInterfaces.measurement_message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.idp.pipeline.PipelineInterfaces.measurement_message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.idp.pipeline.PipelineInterfaces.measurement_message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.idp.pipeline.PipelineInterfaces.measurement_message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static de.idp.pipeline.PipelineInterfaces.measurement_message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static de.idp.pipeline.PipelineInterfaces.measurement_message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static de.idp.pipeline.PipelineInterfaces.measurement_message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static de.idp.pipeline.PipelineInterfaces.measurement_message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static de.idp.pipeline.PipelineInterfaces.measurement_message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(de.idp.pipeline.PipelineInterfaces.measurement_message prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * measurement_message
     * </pre>
     *
     * Protobuf type {@code provenance_system.measurement_message}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:provenance_system.measurement_message)
        de.idp.pipeline.PipelineInterfaces.measurement_messageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return de.idp.pipeline.PipelineInterfaces.internal_static_provenance_system_measurement_message_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return de.idp.pipeline.PipelineInterfaces.internal_static_provenance_system_measurement_message_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                de.idp.pipeline.PipelineInterfaces.measurement_message.class, de.idp.pipeline.PipelineInterfaces.measurement_message.Builder.class);
      }

      // Construct using de.idp.pipeline.PipelineInterfaces.measurement_message.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        meterId_ = "";

        metricId_ = "";

        timestamp_ = 0L;

        value_ = 0D;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return de.idp.pipeline.PipelineInterfaces.internal_static_provenance_system_measurement_message_descriptor;
      }

      public de.idp.pipeline.PipelineInterfaces.measurement_message getDefaultInstanceForType() {
        return de.idp.pipeline.PipelineInterfaces.measurement_message.getDefaultInstance();
      }

      public de.idp.pipeline.PipelineInterfaces.measurement_message build() {
        de.idp.pipeline.PipelineInterfaces.measurement_message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public de.idp.pipeline.PipelineInterfaces.measurement_message buildPartial() {
        de.idp.pipeline.PipelineInterfaces.measurement_message result = new de.idp.pipeline.PipelineInterfaces.measurement_message(this);
        result.meterId_ = meterId_;
        result.metricId_ = metricId_;
        result.timestamp_ = timestamp_;
        result.value_ = value_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof de.idp.pipeline.PipelineInterfaces.measurement_message) {
          return mergeFrom((de.idp.pipeline.PipelineInterfaces.measurement_message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(de.idp.pipeline.PipelineInterfaces.measurement_message other) {
        if (other == de.idp.pipeline.PipelineInterfaces.measurement_message.getDefaultInstance()) return this;
        if (!other.getMeterId().isEmpty()) {
          meterId_ = other.meterId_;
          onChanged();
        }
        if (!other.getMetricId().isEmpty()) {
          metricId_ = other.metricId_;
          onChanged();
        }
        if (other.getTimestamp() != 0L) {
          setTimestamp(other.getTimestamp());
        }
        if (other.getValue() != 0D) {
          setValue(other.getValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        de.idp.pipeline.PipelineInterfaces.measurement_message parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (de.idp.pipeline.PipelineInterfaces.measurement_message) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object meterId_ = "";
      /**
       * <code>string meter_id = 1;</code>
       */
      public java.lang.String getMeterId() {
        java.lang.Object ref = meterId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          meterId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string meter_id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getMeterIdBytes() {
        java.lang.Object ref = meterId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          meterId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string meter_id = 1;</code>
       */
      public Builder setMeterId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        meterId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string meter_id = 1;</code>
       */
      public Builder clearMeterId() {
        
        meterId_ = getDefaultInstance().getMeterId();
        onChanged();
        return this;
      }
      /**
       * <code>string meter_id = 1;</code>
       */
      public Builder setMeterIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        meterId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object metricId_ = "";
      /**
       * <code>string metric_id = 2;</code>
       */
      public java.lang.String getMetricId() {
        java.lang.Object ref = metricId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          metricId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string metric_id = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMetricIdBytes() {
        java.lang.Object ref = metricId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          metricId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string metric_id = 2;</code>
       */
      public Builder setMetricId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        metricId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string metric_id = 2;</code>
       */
      public Builder clearMetricId() {
        
        metricId_ = getDefaultInstance().getMetricId();
        onChanged();
        return this;
      }
      /**
       * <code>string metric_id = 2;</code>
       */
      public Builder setMetricIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        metricId_ = value;
        onChanged();
        return this;
      }

      private long timestamp_ ;
      /**
       * <code>int64 timestamp = 3;</code>
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>int64 timestamp = 3;</code>
       */
      public Builder setTimestamp(long value) {
        
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 timestamp = 3;</code>
       */
      public Builder clearTimestamp() {
        
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      private double value_ ;
      /**
       * <code>double value = 4;</code>
       */
      public double getValue() {
        return value_;
      }
      /**
       * <code>double value = 4;</code>
       */
      public Builder setValue(double value) {
        
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double value = 4;</code>
       */
      public Builder clearValue() {
        
        value_ = 0D;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:provenance_system.measurement_message)
    }

    // @@protoc_insertion_point(class_scope:provenance_system.measurement_message)
    private static final de.idp.pipeline.PipelineInterfaces.measurement_message DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new de.idp.pipeline.PipelineInterfaces.measurement_message();
    }

    public static de.idp.pipeline.PipelineInterfaces.measurement_message getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<measurement_message>
        PARSER = new com.google.protobuf.AbstractParser<measurement_message>() {
      public measurement_message parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new measurement_message(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<measurement_message> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<measurement_message> getParserForType() {
      return PARSER;
    }

    public de.idp.pipeline.PipelineInterfaces.measurement_message getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface replyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:provenance_system.reply)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string response_code = 1;</code>
     */
    java.lang.String getResponseCode();
    /**
     * <code>string response_code = 1;</code>
     */
    com.google.protobuf.ByteString
        getResponseCodeBytes();
  }
  /**
   * Protobuf type {@code provenance_system.reply}
   */
  public  static final class reply extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:provenance_system.reply)
      replyOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use reply.newBuilder() to construct.
    private reply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private reply() {
      responseCode_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private reply(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              responseCode_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return de.idp.pipeline.PipelineInterfaces.internal_static_provenance_system_reply_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return de.idp.pipeline.PipelineInterfaces.internal_static_provenance_system_reply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              de.idp.pipeline.PipelineInterfaces.reply.class, de.idp.pipeline.PipelineInterfaces.reply.Builder.class);
    }

    public static final int RESPONSE_CODE_FIELD_NUMBER = 1;
    private volatile java.lang.Object responseCode_;
    /**
     * <code>string response_code = 1;</code>
     */
    public java.lang.String getResponseCode() {
      java.lang.Object ref = responseCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        responseCode_ = s;
        return s;
      }
    }
    /**
     * <code>string response_code = 1;</code>
     */
    public com.google.protobuf.ByteString
        getResponseCodeBytes() {
      java.lang.Object ref = responseCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        responseCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getResponseCodeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, responseCode_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getResponseCodeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, responseCode_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof de.idp.pipeline.PipelineInterfaces.reply)) {
        return super.equals(obj);
      }
      de.idp.pipeline.PipelineInterfaces.reply other = (de.idp.pipeline.PipelineInterfaces.reply) obj;

      boolean result = true;
      result = result && getResponseCode()
          .equals(other.getResponseCode());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RESPONSE_CODE_FIELD_NUMBER;
      hash = (53 * hash) + getResponseCode().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static de.idp.pipeline.PipelineInterfaces.reply parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.idp.pipeline.PipelineInterfaces.reply parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.idp.pipeline.PipelineInterfaces.reply parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.idp.pipeline.PipelineInterfaces.reply parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.idp.pipeline.PipelineInterfaces.reply parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.idp.pipeline.PipelineInterfaces.reply parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.idp.pipeline.PipelineInterfaces.reply parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static de.idp.pipeline.PipelineInterfaces.reply parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static de.idp.pipeline.PipelineInterfaces.reply parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static de.idp.pipeline.PipelineInterfaces.reply parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static de.idp.pipeline.PipelineInterfaces.reply parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static de.idp.pipeline.PipelineInterfaces.reply parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(de.idp.pipeline.PipelineInterfaces.reply prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code provenance_system.reply}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:provenance_system.reply)
        de.idp.pipeline.PipelineInterfaces.replyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return de.idp.pipeline.PipelineInterfaces.internal_static_provenance_system_reply_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return de.idp.pipeline.PipelineInterfaces.internal_static_provenance_system_reply_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                de.idp.pipeline.PipelineInterfaces.reply.class, de.idp.pipeline.PipelineInterfaces.reply.Builder.class);
      }

      // Construct using de.idp.pipeline.PipelineInterfaces.reply.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        responseCode_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return de.idp.pipeline.PipelineInterfaces.internal_static_provenance_system_reply_descriptor;
      }

      public de.idp.pipeline.PipelineInterfaces.reply getDefaultInstanceForType() {
        return de.idp.pipeline.PipelineInterfaces.reply.getDefaultInstance();
      }

      public de.idp.pipeline.PipelineInterfaces.reply build() {
        de.idp.pipeline.PipelineInterfaces.reply result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public de.idp.pipeline.PipelineInterfaces.reply buildPartial() {
        de.idp.pipeline.PipelineInterfaces.reply result = new de.idp.pipeline.PipelineInterfaces.reply(this);
        result.responseCode_ = responseCode_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof de.idp.pipeline.PipelineInterfaces.reply) {
          return mergeFrom((de.idp.pipeline.PipelineInterfaces.reply)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(de.idp.pipeline.PipelineInterfaces.reply other) {
        if (other == de.idp.pipeline.PipelineInterfaces.reply.getDefaultInstance()) return this;
        if (!other.getResponseCode().isEmpty()) {
          responseCode_ = other.responseCode_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        de.idp.pipeline.PipelineInterfaces.reply parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (de.idp.pipeline.PipelineInterfaces.reply) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object responseCode_ = "";
      /**
       * <code>string response_code = 1;</code>
       */
      public java.lang.String getResponseCode() {
        java.lang.Object ref = responseCode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          responseCode_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string response_code = 1;</code>
       */
      public com.google.protobuf.ByteString
          getResponseCodeBytes() {
        java.lang.Object ref = responseCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          responseCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string response_code = 1;</code>
       */
      public Builder setResponseCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        responseCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string response_code = 1;</code>
       */
      public Builder clearResponseCode() {
        
        responseCode_ = getDefaultInstance().getResponseCode();
        onChanged();
        return this;
      }
      /**
       * <code>string response_code = 1;</code>
       */
      public Builder setResponseCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        responseCode_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:provenance_system.reply)
    }

    // @@protoc_insertion_point(class_scope:provenance_system.reply)
    private static final de.idp.pipeline.PipelineInterfaces.reply DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new de.idp.pipeline.PipelineInterfaces.reply();
    }

    public static de.idp.pipeline.PipelineInterfaces.reply getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<reply>
        PARSER = new com.google.protobuf.AbstractParser<reply>() {
      public reply parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new reply(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<reply> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<reply> getParserForType() {
      return PARSER;
    }

    public de.idp.pipeline.PipelineInterfaces.reply getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_provenance_system_Grid_data_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_provenance_system_Grid_data_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_provenance_system_measurement_message_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_provenance_system_measurement_message_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_provenance_system_reply_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_provenance_system_reply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n%proto_files/pipeline_interfaces.proto\022" +
      "\021provenance_system\"H\n\tGrid_data\022;\n\013measu" +
      "rement\030\001 \001(\0132&.provenance_system.measure" +
      "ment_message\"\\\n\023measurement_message\022\020\n\010m" +
      "eter_id\030\001 \001(\t\022\021\n\tmetric_id\030\002 \001(\t\022\021\n\ttime" +
      "stamp\030\003 \001(\003\022\r\n\005value\030\004 \001(\001\"\036\n\005reply\022\025\n\rr" +
      "esponse_code\030\001 \001(\t2R\n\007gateway\022G\n\tpush_da" +
      "ta\022\034.provenance_system.Grid_data\032\030.prove" +
      "nance_system.reply\"\000(\001B\021\n\017de.idp.pipelin" +
      "eb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_provenance_system_Grid_data_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_provenance_system_Grid_data_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_provenance_system_Grid_data_descriptor,
        new java.lang.String[] { "Measurement", });
    internal_static_provenance_system_measurement_message_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_provenance_system_measurement_message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_provenance_system_measurement_message_descriptor,
        new java.lang.String[] { "MeterId", "MetricId", "Timestamp", "Value", });
    internal_static_provenance_system_reply_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_provenance_system_reply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_provenance_system_reply_descriptor,
        new java.lang.String[] { "ResponseCode", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
