version: '3'

#TOPO: Issue #77
# 	  C --> L --> N
# A,B --> D --> L --> N		
# E,F --> G --> L --> N
#		  --> N --> endpoint
#   H --> I -->	M --> N
#	J,K --> M --> N
volumes:
    provenancesensordata:
        external: true

services:
    cassandra:
        image: cassandra:latest

    idprovider:
        image: cloudproto/idprovider:latest
        environment:
            - START_ID=31400010000000000

    sensorGroupA:
        image: cloudproto/sensor:latest
        depends_on:
            - gatewayA
            - idprovider
        restart: always
        volumes:
            - provenancesensordata:/mnt
        environment:
            - SENSOR_PARAMETERS=-sourceFolder /mnt/oneday -sensorIdProvider idprovider:8080 -frequency 1000 -targetAddress gatewayA:50051 -targetType grpc-pipeline
            - STARTUP_DELAY=30
    sensorGroupB:
        image: cloudproto/sensor:latest
        depends_on:
            - gatewayB
            - idprovider
        restart: always
        volumes:
            - provenancesensordata:/mnt
        environment:
            - SENSOR_PARAMETERS=-sourceFolder /mnt/oneday -sensorIdProvider idprovider:8080 -frequency 1000 -targetAddress gatewayB:50051 -targetType grpc-pipeline
            - STARTUP_DELAY=30
    sensorGroupC:
        image: cloudproto/sensor:latest
        depends_on:
            - gatewayC
            - idprovider
        restart: always
        volumes:
            - provenancesensordata:/mnt
        environment:
            - SENSOR_PARAMETERS=-sourceFolder /mnt/oneday -sensorIdProvider idprovider:8080 -frequency 1000 -targetAddress gatewayC:50051 -targetType grpc-pipeline
            - STARTUP_DELAY=30
    sensorGroupE:
        image: cloudproto/sensor:latest
        depends_on:
            - gatewayE
            - idprovider
        restart: always
        volumes:
            - provenancesensordata:/mnt
        environment:
            - SENSOR_PARAMETERS=-sourceFolder /mnt/oneday -sensorIdProvider idprovider:8080 -frequency 1000 -targetAddress gatewayE:50051 -targetType grpc-pipeline
            - STARTUP_DELAY=30

    sensorGroupF:
        image: cloudproto/sensor:latest
        depends_on:
            - gatewayF
            - idprovider
        restart: always
        volumes:
            - provenancesensordata:/mnt
        environment:
            - SENSOR_PARAMETERS=-sourceFolder /mnt/oneday -sensorIdProvider idprovider:8080 -frequency 1000 -targetAddress gatewayF:50051 -targetType grpc-pipeline
            - STARTUP_DELAY=30
    sensorGroupG:
        image: cloudproto/sensor:latest
        depends_on:
            - gatewayG
            - idprovider
        restart: always
        volumes:
            - provenancesensordata:/mnt
        environment:
            - SENSOR_PARAMETERS=-sourceFolder /mnt/oneday -sensorIdProvider idprovider:8080 -frequency 1000 -targetAddress gatewayG:50051 -targetType grpc-pipeline
            - STARTUP_DELAY=30
    sensorGroupH:
        image: cloudproto/sensor:latest
        depends_on:
            - gatewayH
            - idprovider
        restart: always
        volumes:
            - provenancesensordata:/mnt
        environment:
            - SENSOR_PARAMETERS=-sourceFolder /mnt/oneday -sensorIdProvider idprovider:8080 -frequency 1000 -targetAddress gatewayH:50051 -targetType grpc-pipeline
            - STARTUP_DELAY=30
    sensorGroupI:
        image: cloudproto/sensor:latest
        depends_on:
            - gatewayI
            - idprovider
        restart: always
        volumes:
            - provenancesensordata:/mnt
        environment:
            - SENSOR_PARAMETERS=-sourceFolder /mnt/oneday -sensorIdProvider idprovider:8080 -frequency 1000 -targetAddress gatewayI:50051 -targetType grpc-pipeline
            - STARTUP_DELAY=30

    sensorGroupJ:
        image: cloudproto/sensor:latest
        depends_on:
            - gatewayJ
            - idprovider
        restart: always
        volumes:
            - provenancesensordata:/mnt
        environment:
            - SENSOR_PARAMETERS=-sourceFolder /mnt/oneday -sensorIdProvider idprovider:8080 -frequency 1000 -targetAddress gatewayJ:50051 -targetType grpc-pipeline
            - STARTUP_DELAY=30
    sensorGroupK:
        image: cloudproto/sensor:latest
        depends_on:
            - gatewayK
            - idprovider
        restart: always
        volumes:
            - provenancesensordata:/mnt
        environment:
            - SENSOR_PARAMETERS=-sourceFolder /mnt/oneday -sensorIdProvider idprovider:8080 -frequency 1000 -targetAddress gatewayK:50051 -targetType grpc-pipeline
            - STARTUP_DELAY=30

    gatewayA:
        image: cloudproto/pipeline_component:latest
        environment:
            - CASSANDRA_HOST=cassandra
            - NODE_ID=000001
            - NODE_NAME=gatewayA
            - ARGUMENTS=--port 50051 --host_next gatewayD --port_next 50051
            - STARTUP_DELAY=20

    gatewayB:
        image: cloudproto/pipeline_component:latest
        environment:
            - CASSANDRA_HOST=cassandra
            - NODE_ID=000002
            - NODE_NAME=gatewayB
            - ARGUMENTS=--port 50051 --host_next gatewayD --port_next 50051
            - STARTUP_DELAY=20

    gatewayC:
        image: cloudproto/pipeline_component:latest
        environment:
            - CASSANDRA_HOST=cassandra
            - NODE_ID=000003
            - NODE_NAME=gatewayC
            - ARGUMENTS=--port 50051 --host_next gatewayL --port_next 50051
            - STARTUP_DELAY=20
    gatewayD:
        image: cloudproto/pipeline_component:latest
        environment:
            - CASSANDRA_HOST=cassandra
            - NODE_ID=000004
            - NODE_NAME=gatewayD
            - ARGUMENTS=--port 50051 --host_next gatewayL --port_next 50051
            - STARTUP_DELAY=20
    gatewayE:
        image: cloudproto/pipeline_component:latest
        environment:
            - CASSANDRA_HOST=cassandra
            - NODE_ID=000005
            - NODE_NAME=gatewayE
            - ARGUMENTS=--port 50051 --host_next gatewayG --port_next 50051
            - STARTUP_DELAY=20
    gatewayF:
        image: cloudproto/pipeline_component:latest
        environment:
            - CASSANDRA_HOST=cassandra
            - NODE_ID=000006
            - NODE_NAME=gatewayF
            - ARGUMENTS=--port 50051 --host_next gatewayG --port_next 50051
            - STARTUP_DELAY=20
    gatewayG:
        image: cloudproto/pipeline_component:latest
        environment:
            - CASSANDRA_HOST=cassandra
            - NODE_ID=000007
            - NODE_NAME=gatewayG
            - ARGUMENTS=--port 50051 --host_next gatewayL --port_next 50051
            - STARTUP_DELAY=20
    gatewayH:
        image: cloudproto/pipeline_component:latest
        environment:
            - CASSANDRA_HOST=cassandra
            - NODE_ID=000008
            - NODE_NAME=gatewayH
            - ARGUMENTS=--port 50051 --host_next gatewayI --port_next 50051
            - STARTUP_DELAY=20
    gatewayI:
        image: cloudproto/pipeline_component:latest
        environment:
            - CASSANDRA_HOST=cassandra
            - NODE_ID=000009
            - NODE_NAME=gatewayI
            - ARGUMENTS=--port 50051 --host_next gatewayM --port_next 50051
            - STARTUP_DELAY=20
    gatewayJ:
        image: cloudproto/pipeline_component:latest
        environment:
            - CASSANDRA_HOST=cassandra
            - NODE_ID=000010
            - NODE_NAME=gatewayJ
            - ARGUMENTS=--port 50051 --host_next gatewayM --port_next 50051
            - STARTUP_DELAY=20
    gatewayK:
        image: cloudproto/pipeline_component:latest
        environment:
            - CASSANDRA_HOST=cassandra
            - NODE_ID=000011
            - NODE_NAME=gatewayK
            - ARGUMENTS=--port 50051 --host_next gatewayM --port_next 50051
            - STARTUP_DELAY=20


    gatewayL:
        image: cloudproto/pipeline_component:latest
        environment:
            - CASSANDRA_HOST=cassandra
            - NODE_ID=000012
            - NODE_NAME=gatewayL
            - ARGUMENTS=--port 50051 --host_next gatewayN --port_next 50051
            - STARTUP_DELAY=20
    gatewayM:
        image: cloudproto/pipeline_component:latest
        environment:
            - CASSANDRA_HOST=cassandra
            - NODE_ID=000013
            - NODE_NAME=gatewayM
            - ARGUMENTS=--port 50051 --host_next gatewayN --port_next 50051
            - STARTUP_DELAY=20
    gatewayN:
        image: cloudproto/pipeline_component:latest
        environment:
            - CASSANDRA_HOST=cassandra
            - NODE_ID=000014
            - NODE_NAME=gatewayN
            - ARGUMENTS=--port 50051 --host_next endpoint --port_next 50051
            - STARTUP_DELAY=20
    endpoint:
        image: cloudproto/pipeline_component:latest
        environment:
            - CASSANDRA_HOST=cassandra
            - STARTUP_DELAY=20
            - ARGUMENTS=--port 50051
            - NODE_ID=000015
            - NODE_NAME=endpoint
