version: '3'
services:
    source:
        image: cloudproto/sensor:latest
        depends_on:
            - gateway
        restart: always
#        command: ["./wait-for-it.sh", "gateway:50051", "--", "./smemu", "-sourceFolder", "data/20170210", "-targetAddress", "gateway:50051" , "-targetType", "grpc-pipeline"]
        command: [ "sh", "-c", "sleep 10 && ./smemu -sourceFolder data/20170210 -targetAddress gateway:50051 -targetType grpc-pipeline" ]
    gateway:
        image: cloudproto/pipeline_component:latest
        environment:
            - "ARGUMENTS=--port 50051 --host_next endpoint --port_next 50051"
        depends_on:
            - endpoint
    endpoint:
       image: cloudproto/pipeline_component:latest
       environment:
           - "ARGUMENTS=--port 50051 --verbose"

    backend:
        image: provenance-backend:latest
    
    frontend:
        image: provenance-frontend:latest
        environment:
            - "BACKEND_HOST=backend:5000"
        ports:
            - "8080:8080"
        depends_on:
            - backend
