version: '3'
services:
    cassandra:
        image: cassandra:latest
    backend:
        image: cloudproto/provenancebackend:latest
        environment:
            - DB_IP=cassandra
        depends_on:
            - cassandra
    frontend:
        image: cloudproto/provenancefrontend:latest
        environment:
            - "BACKEND_HOST=backend:5000"
        ports:
            - "8080:8080"
        depends_on:
            - backend
