version: '3'

# to use the provenance volume it's mandatory to install the rexray/s3 plugin
# docker plugin install rexray/s3fs:latest S3FS_ACCESSKEY=XXXXX S3FS_SECRETKEY=XXXXXX

volumes:
    provenancesensordata:
        external: true

services:
    cassandra:
        image: cassandra:latest

## sensor container can retrieve unique sensor ids from this service
    idprovider:
        image: cloudproto/idprovider:latest
        environment:
            - START_ID=31400010000000000

    sensorGroupA:
        image: cloudproto/sensor:latest
        depends_on:
            - gateway
            - idprovider
        restart: always
        volumes:
            - provenancesensordata:/mnt
        environment:
            - SENSOR_PARAMETERS=-sourceFolder /mnt/oneday -sensorIdProvider idprovider:8080 -frequency 1000 -targetAddress gateway:50051 -targetType grpc-pipeline
            - STARTUP_DELAY=30


    gateway:
        image: cloudproto/pipeline_component:latest
        environment:
            - CASSANDRA_HOST=cassandra
            - NODE_ID=000001
            - NODE_NAME=gateway
            - ARGUMENTS=--port 50051 --host_next endpoint --port_next 50051
            - STARTUP_DELAY=20
        depends_on:
            - endpoint
            - cassandra

    endpoint:
        image: cloudproto/pipeline_component:latest
        depends_on:
            - cassandra
        environment:
            - CASSANDRA_HOST=cassandra
            - ARGUMENTS=--port 50051 --verbose
            - NODE_ID=000002
            - NODE_NAME=endpoint
            - STARTUP_DELAY=20

