version: '3'
services:
    source:
        image: cloudproto/sensor:latest
        depends_on:
            - gateway
        restart: always
        command: [ "sh", "-c", "sleep 10 && ./smemu -sourceFolder data/20170210 -targetAddress gateway:50051 -targetType grpc-pipeline" ]
    gateway:
        image: pipeline_java:latest
        environment:
            - "ARGUMENTS=--port 50051 --host_next gateway2 --port_next 50051"
        depends_on:
            - endpoint
    gateway2:
#       use the local build image
#       image: pipeline_java:latest

#       use the deployed image
        image: pipeline_java:latest
        environment:
            - "ARGUMENTS=--port 50051 --host_next endpoint --port_next 50051"
        depends_on:
            - endpoint


    endpoint:
       image: pipeline_java:latest
       environment:
           - "ARGUMENTS=--port 50051 --verbose"
