version: '3'
services:
    backend:
        image: provenance-backend:latest
    frontend:
        image: provenance-frontend:latest
        environment:
            - "BACKEND_HOST=backend:5000"
        ports:
            - "8080:8080"
        depends_on:
            - backend
