version: '3'

services:
    source:
        image: cloudproto/sensor:s3
        depends_on:
            - gateway
        restart: always
        privileged: true
        environment:
            - BUCKET=provenancesensordata:oneday
            - AWS_ACCESS_KEY_ID=ADD_YOUR_ACCESS_KEY
            - AWS_SECRET_ACCESS_KEY=ADD_YOUR_SECRET_KEY
            - REGION=eu-central-1
            - SENSOR_PARAMETERS=-sourceFolder /mnt/s3/31400010000000000 -targetAddress gateway:50051 -targetType grpc-pipeline
            - STARTUP_DELAY=10
    gateway:
        image: cloudproto/pipeline_component:latest
        environment:
            - "ARGUMENTS=--port 50051 --host_next endpoint --port_next 50051"
        depends_on:
            - endpoint
    endpoint:
       image: cloudproto/pipeline_component:latest
       environment:
           - "ARGUMENTS=--port 50051 --verbose"
