version: '3'

#TOPO:
# 	 
# A --> E --> I	--> K
# B --> F --> I --> K
#		--> K --> endpoint
# C --> G --> J --> K  
# D --> H --> J --> K
volumes:
    provenancesensordata:
        external: true

services:
    cassandra:
        image: cassandra:latest
        ports:
            - "9042:9042"

    idprovider:
        image: cloudproto/idprovider:latest
        environment:
            - START_ID=31400010000000000

    sensorGroupA:
        image: cloudproto/sensor:latest
        depends_on:
            - gatewayA
            - idprovider
        restart: always
        volumes:
            - provenancesensordata:/mnt
        environment:
            - SENSOR_PARAMETERS=-sourceFolder /mnt/oneday -sensorIdProvider idprovider:8080 -frequency 1000 -targetAddress gatewayA:50051 -targetType grpc-pipeline
            - STARTUP_DELAY=30
    sensorGroupB:
        image: cloudproto/sensor:latest
        depends_on:
            - gatewayB
            - idprovider
        restart: always
        volumes:
            - provenancesensordata:/mnt
        environment:
            - SENSOR_PARAMETERS=-sourceFolder /mnt/oneday -sensorIdProvider idprovider:8080 -frequency 1000 -targetAddress gatewayB:50051 -targetType grpc-pipeline
            - STARTUP_DELAY=30
    sensorGroupC:
        image: cloudproto/sensor:latest
        depends_on:
            - gatewayC
            - idprovider
        restart: always
        volumes:
            - provenancesensordata:/mnt
        environment:
            - SENSOR_PARAMETERS=-sourceFolder /mnt/oneday -sensorIdProvider idprovider:8080 -frequency 1000 -targetAddress gatewayC:50051 -targetType grpc-pipeline
            - STARTUP_DELAY=30
    sensorGroupD:
        image: cloudproto/sensor:latest
        depends_on:
            - gatewayD
            - idprovider
        restart: always
        volumes:
            - provenancesensordata:/mnt
        environment:
            - SENSOR_PARAMETERS=-sourceFolder /mnt/oneday -sensorIdProvider idprovider:8080 -frequency 1000 -targetAddress gatewayD:50051 -targetType grpc-pipeline
            - STARTUP_DELAY=30

    gatewayA:
        image: cloudproto/pipeline_component:latest
        environment:
            - CASSANDRA_HOST=cassandra
            - NODE_ID=000001
            - NODE_NAME=gatewayA
            - ARGUMENTS=--port 50051 --host_next gatewayE --port_next 50051
            - STARTUP_DELAY=20

    gatewayB:
        image: cloudproto/pipeline_component:latest
        environment:
            - CASSANDRA_HOST=cassandra
            - NODE_ID=000002
            - NODE_NAME=gatewayB
            - ARGUMENTS=--port 50051 --host_next gatewayF --port_next 50051
            - STARTUP_DELAY=20

    gatewayC:
        image: cloudproto/pipeline_component:latest
        environment:
            - CASSANDRA_HOST=cassandra
            - NODE_ID=000003
            - NODE_NAME=gatewayC
            - ARGUMENTS=--port 50051 --host_next gatewayG --port_next 50051
            - STARTUP_DELAY=20
    gatewayD:
        image: cloudproto/pipeline_component:latest
        environment:
            - CASSANDRA_HOST=cassandra
            - NODE_ID=000004
            - NODE_NAME=gatewayD
            - ARGUMENTS=--port 50051 --host_next gatewayH --port_next 50051
            - STARTUP_DELAY=20
    gatewayE:
        image: cloudproto/pipeline_component:latest
        environment:
            - CASSANDRA_HOST=cassandra
            - NODE_ID=000005
            - NODE_NAME=gatewayE
            - ARGUMENTS=--port 50051 --host_next gatewayI --port_next 50051
            - STARTUP_DELAY=20
    gatewayF:
        image: cloudproto/pipeline_component:latest
        environment:
            - CASSANDRA_HOST=cassandra
            - NODE_ID=000006
            - NODE_NAME=gatewayF
            - ARGUMENTS=--port 50051 --host_next gatewayI --port_next 50051
            - STARTUP_DELAY=20
    gatewayG:
        image: cloudproto/pipeline_component:latest
        environment:
            - CASSANDRA_HOST=cassandra
            - NODE_ID=000007
            - NODE_NAME=gatewayG
            - ARGUMENTS=--port 50051 --host_next gatewayJ --port_next 50051
            - STARTUP_DELAY=20
    gatewayH:
        image: cloudproto/pipeline_component:latest
        environment:
            - CASSANDRA_HOST=cassandra
            - NODE_ID=000008
            - NODE_NAME=gatewayH
            - ARGUMENTS=--port 50051 --host_next gatewayJ --port_next 50051
            - STARTUP_DELAY=20
    gatewayI:
        image: cloudproto/pipeline_component:latest
        environment:
            - CASSANDRA_HOST=cassandra
            - NODE_ID=000009
            - NODE_NAME=gatewayI
            - ARGUMENTS=--port 50051 --host_next gatewayK --port_next 50051
            - STARTUP_DELAY=20
    gatewayJ:
        image: cloudproto/pipeline_component:latest
        environment:
            - CASSANDRA_HOST=cassandra
            - NODE_ID=000010
            - NODE_NAME=gatewayJ
            - ARGUMENTS=--port 50051 --host_next gatewayK --port_next 50051
            - STARTUP_DELAY=20
    gatewayK:
        image: cloudproto/pipeline_component:latest
        environment:
            - CASSANDRA_HOST=cassandra
            - NODE_ID=000011
            - NODE_NAME=gatewayK
            - ARGUMENTS=--port 50051 --host_next endpoint --port_next 50051
            - STARTUP_DELAY=20
    endpoint:
        image: cloudproto/pipeline_component:latest
        environment:
            - CASSANDRA_HOST=cassandra
            - STARTUP_DELAY=20
            - ARGUMENTS=--port 50051
            - NODE_ID=000012
            - NODE_NAME=endpoint
