version: '3'
services:
    sourceA:
        image: cloudproto/sensor:latest
        environment:
            - SENSOR_PARAMETERS=-sourceFolder data/20170210 -frequency 1000 -targetAddress gatewayA:50051 -targetType grpc-pipeline
            - STARTUP_DELAY=60
        logging:
          driver: "none"

    gatewayA:
        image: cloudproto/pipeline_component:latest
        environment:
            - STARTUP_DELAY=40
            - ARGUMENTS=--port 50051 --host_next gatewayC --port_next 50051 --storagetime 100 --no_prov
        logging:
          driver: "none"

    sourceB:
        image: cloudproto/sensor:latest
        environment:
            - SENSOR_PARAMETERS=-sourceFolder data/20170210 -frequency 1000 -targetAddress gatewayB:50051 -targetType grpc-pipeline
            - STARTUP_DELAY=60
        logging:
          driver: "none"

    gatewayB:
        image: cloudproto/pipeline_component:latest
        environment:
            - STARTUP_DELAY=40
            - ARGUMENTS=--port 50051 --host_next gatewayC --port_next 50051 --storagetime 100 --no_prov
        logging:
          driver: "none"

    gatewayC:
        image: cloudproto/pipeline_component:latest
        environment:
            - STARTUP_DELAY=40
            - ARGUMENTS=--port 50051 --host_next endpoint --port_next 50051 --storagetime 100 --no_prov
        logging:
          driver: "none"

    endpoint:
        image: cloudproto/pipeline_component:latest
        environment:
            - STARTUP_DELAY=30
            - ARGUMENTS=--port 50051 --storagetime 100 --no_prov
        logging:
          driver: "none"
