version: '3'
services:
    cassandra:
        image: cassandra:latest
    source:
        image: cloudproto/sensor:latest
        environment:
            - SENSOR_PARAMETERS=-sourceFolder data/20170210 -frequency 1000 -targetAddress endpoint:50051 -targetType grpc-pipeline
            - STARTUP_DELAY=60
        logging:
          driver: "none"
    endpoint:
        image: cloudproto/pipeline_component:latest
        depends_on:
            - cassandra
        environment:
            - STARTUP_DELAY=30
            - CASSANDRA_HOST=cassandra
            - ARGUMENTS=--port 50051 --storagetime 100
            - NODE_ID=000002
            - NODE_NAME=endpoint
            - METRICS=meterid,metricid,loc,line,class,app,ctime,stime,rtime
            - BUFFER_CAPACITY=1
        logging:
          driver: "none"
